global using MediatR;
global using Order.Application.UseCases.BasketItems.Commands;
global using Order.Application.Abstractions;
global using Microsoft.EntityFrameworkCore;
global using Order.Application.UseCases.BasketItems.Queries;
global using Order.Application.UseCases.Baskets.Commands;
global using Order.Application.UseCases.Baskets.Queries;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
